services:
  - type: web
    name: voice-memorial-qr
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
    healthCheckPath: "/health"
